MvcBlogum/MvcBlogPortfolio/Controllers/MakaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBlogPortfolio.App_Classes;

namespace MvcBlogPortfolio.Controllers
{
    using Models;
    using MvcBlogPortfolio.Tools;
    using System.Drawing;
    using System.IO;
    using System.Web.Helpers;

    [Authorize]
    public class MakaleController : Controller
    {
        Myblog myblog = new Myblog();
        dbModelblog db = new dbModelblog();
        Resim rsm = new Resim();
        // GET: Makale
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult Detay(int id)
        {
            var data = db.Makale.FirstOrDefault(x => x.MakaleId == id);
            return View(data);
        }
    
  
        [AllowAnonymous]
        public string Begen(int id)
        {
            Makale mkl = db.Makale.Where(x => x.MakaleId == id).FirstOrDefault();
            mkl.Begeni++;//Begeni +1
            db.SaveChanges();
            return mkl.Begeni.ToString();
        }
        //[AllowAnonymous]
        public string Goruntulendi(int id)
        {
            Makale mkl = db.Makale.FirstOrDefault(x => x.MakaleId == id);
            mkl.GoruntulenmeSayisi++;
            db.SaveChanges();
            return mkl.GoruntulenmeSayisi.ToString();
        }


        [Authorize(Roles = "Admin,Yazar")]
        public ActionResult Ekle()
        {
            ViewBag.Kategoriler = db.Kategori.ToList();
            return View();
        }

        [Authorize(Roles = "Admin,Yazar")]
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Ekle(Makale mkl, HttpPostedFileBase resim)
        {
            try
            {
                Image img = Image.FromStream(resim.InputStream);

                Bitmap kckResim = new Bitmap(img, Setttings.ResimKucukBoyut);
                Bitmap ortaResim = new Bitmap(img, Setttings.ResimOrtaBoyut);
                Bitmap bykResim = new Bitmap(img, Setttings.ResimBuyukBoyut);
                bykResim.Save(Server.MapPath("/Content/MakaleResim/BuyukBoyut/" + resim.FileName));
                ortaResim.Save(Server.MapPath("/Content/MakaleResim/OrtaBoyut/" + resim.FileName));
                kckResim.Save(Server.MapPath("/Content/MakaleResim/KucukBoyut/" + resim.FileName));

                Resim rsm = new Resim();

                rsm.BuyukBoyut = "/Content/MakaleResim/BuyukBoyut/" + resim.FileName;
                rsm.OrtaBoyut = "/Content/MakaleResim/OrtaBoyut/" + resim.FileName;
                rsm.KucukBoyut = "/Content/MakaleResim/KucukBoyut/" + resim.FileName;
                db.Resim.Add(rsm);
                db.SaveChanges();
                mkl.ResimID = rsm.ResimId;
                mkl.EklenmeTarihi = DateTime.Now;
                mkl.GoruntulenmeSayisi = 0;
                mkl.Begeni = 0;


                int yzrId = db.Kullanicilar.FirstOrDefault(x => x.KullaniciAdi == User.Identity.Name).KullaniciId;
                mkl.KullaniciID = yzrId;
                db.Makale.Add(mkl);
                db.SaveChanges(); 

            }
            catch (Exception )
            {

               
            }

            return RedirectToAction("Index", "Home");
        }


        //[Authorize(Roles ="Admin,Yazar")]
        //public ActionResult Guncelle(int? id)
        //{
        //    myblog.makale = db.Makale.Where(x => x.MakaleId == id).FirstOrDefault();
        //     myblog.kategori= db.Kategori.ToList();
        //    return View(myblog);
        //}
        //[HttpPost]
        //[ValidateInput(false)]
        //[Authorize(Roles ="Admin,Yazar")]
        //public ActionResult Guncelle(Makale mkl,HttpPostedFileBase img,int? id)
        //{
        //    Makale guncelle = db.Makale.Where(x => x.MakaleId == id).FirstOrDefault();
        //        guncelle.KategoriID = mkl.KategoriID;
        //        guncelle.Baslik = mkl.Baslik;
        //        guncelle.Icerik = mkl.Icerik;
        //    guncelle.EklenmeTarihi = DateTime.Now;

        //    db.SaveChanges();
        //    return RedirectToAction("YazarınMakaleleri","Yazar");
        //        //return new RedirectResult("~/Home/Index/" + guncelle.MakaleId);
        //    }

        //public ActionResult Sil(int? id)
        //{

        //    Yorum sil = db.Yorum.Where(x => x.MakaleID == id).FirstOrDefault();
        //    if (sil != null) { 
        //     db.Yorum.Remove(sil);
        //    }

        //    Makale silinen = db.Makale.Where(x => x.MakaleId == id).FirstOrDefault();
        //    db.Makale.Remove(silinen);
        //    db.SaveChanges();
        //    return RedirectToAction("Index","Home");  
        //}

     
        [Authorize(Roles ="Admin,Yazar")]
        public ActionResult YorumYaz(Yorum yrm,int? id)
        {

            Yorum mkl = db.Yorum.Where(x => x.MakaleID == id).FirstOrDefault();
            Yorum yorum = new Yorum();
            yorum.MakaleID = id;
           
            yorum.AdSoyad = yrm.AdSoyad;
            yorum.YorumIcerigi = yrm.YorumIcerigi;
            yorum.EklenmeTarihi = DateTime.Now;
            
            db.Yorum.Add(yorum);
            db.SaveChanges();
            return new RedirectResult("~/Makale/Detay/" + yorum.MakaleID);

        }


    }
}

MvcBlogum/MvcBlogPortfolio/Controllers/YazarController.cs
using MvcBlogPortfolio.App_Classes;
using MvcBlogPortfolio.Models;
using MvcBlogPortfolio.Tools;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MvcBlogPortfolio.Controllers
{
    public class YazarController : Controller
    {
        Myblog myblog = new Myblog();
        dbModelblog db = new dbModelblog();
        Resim rsm = new Resim();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult YazarOl()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YazarOl(Kullanicilar kl,string rdBay,string rdBayan)
        {
            if (!string.IsNullOrEmpty(rdBay))
                kl.Cinsiyet = true;
            if(!string.IsNullOrEmpty(rdBayan))
                kl.Cinsiyet = false;
            kl.Yazar = true;
            kl.Onaylandi = false;
            kl.Aktif = true;
            kl.KayitTarihi = DateTime.Now;
            db.Kullanicilar.Add(kl);
            db.SaveChanges();

            Rol yazar = db.Rol.FirstOrDefault(x => x.RolAdi == "Yazar");
            KullaniciRol kr = new KullaniciRol();
            kr.RolID = yazar.RolId;
            kr.KullaniciID = kl.KullaniciId;
            db.KullaniciRol.Add(kr);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }


        [Authorize(Roles ="Yazar")]
        public ActionResult YazarınMakaleleri()
        {
            int id = Convert.ToInt32(Session["KullaniciId"]); 

                myblog.makaleler = db.Makale.Where(x => x.KullaniciID ==id).ToList();
               return View(myblog);

        }
  
        public ActionResult Sil(int id)
        {
            Kullanicilar silinen = db.Kullanicilar.Where(x => x.KullaniciId == id).FirstOrDefault();
            db.Kullanicilar.Remove(silinen);
            db.SaveChanges();
            return View();
        }

        [Authorize(Roles = "Admin,Yazar")]
        public ActionResult Guncelle(int? id)
        {
            myblog.makale = db.Makale.Where(x => x.MakaleId == id).FirstOrDefault();
            myblog.kategori = db.Kategori.ToList();
            return View(myblog);
        }
        [HttpPost]
        [ValidateInput(false)]
        [Authorize(Roles = "Admin,Yazar")]
        public ActionResult Guncelle(Makale mkl, HttpPostedFileBase img, int? id)
        {
            Makale guncelle = db.Makale.Where(x => x.MakaleId == id).FirstOrDefault();
            guncelle.KategoriID = mkl.KategoriID;
            guncelle.Baslik = mkl.Baslik;
            guncelle.Icerik = mkl.Icerik;
            guncelle.EklenmeTarihi = DateTime.Now;

            db.SaveChanges();
            return RedirectToAction("YazarınMakaleleri", "Yazar");
            //return new RedirectResult("~/Home/Index/" + guncelle.MakaleId);
        }

        public ActionResult MakaleSil(int? id)
        {

            Yorum sil = db.Yorum.Where(x => x.MakaleID == id).FirstOrDefault();
            Etiket etiket = db.Etiket.Where(x => x.EtiketId == id).FirstOrDefault();
            if (sil != null)
            {
                db.Yorum.Remove(sil);
             
            }
            Makale silinen = db.Makale.Where(x => x.MakaleId == id).FirstOrDefault();
            db.Makale.Remove(silinen);
            db.SaveChanges();
            return RedirectToAction("YazarınMakaleleri", "Yazar");
        }

    }
}

MvcBlogum/MvcBlogPortfolio/Views/Yazar/Guncelle.cshtml
@model MvcBlogPortfolio.Tools.Myblog
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<script src="~/ckeditor/ckeditor.js"></script>
<script src="~/ckfinder/ckfinder.js"></script>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<form action="~/Yazar/Guncelle/@Model.makale.MakaleId" method="post" enctype="multipart/form-data">
    <table>
        <tr>
            <td> Başlık:</td>
            <td><input type="text" id="Baslik" name="Baslik" value="@Model.makale.Baslik" /></td>
        </tr>
        <tr>
            <td>İçerik:</td>

            <td><textarea id="Icerik" name="Icerik">@Model.makale.Icerik</textarea></td>
        </tr>
        <tr>
            <td>Ekleme Tarihi:</td>

            <td><input type="datetime" id="EklemeTarihi" name="EklemeTarihi" value="@Model.makale.EklenmeTarihi" /></td>
        </tr>
        <tr>
            <td>Kategori:</td>
            <td>
                <select id="KategoriID" name="KategoriID">
                    @foreach (var item in Model.kategori)
                    {
                        if (item.KategoriId == Model.makale.KategoriID)
                        {
                            <option value="@item.KategoriId" selected>@item.KategoriAdi</option>
                        }
                        else
                        {
                            <option value="@item.KategoriId">@item.KategoriAdi</option>}

                    }
                </select>
            </td>
        </tr>
        <tr>
            <td>Resim:</td>
            <td>
                <input type="file" name="resim" value=@Model.makale.Resim.KucukBoyut />
            </td>
        </tr>


        <tr>
            <td></td>
            <td>
                <input type="submit" name="name" value="Ekle" />
            </td>
        </tr>
    </table>
</form>
<script type="text/javascript">
    var editor = CKEDITOR.replace('Icerik');
    CKFinder.setupCKEditor(editor, '/ckfinder/');
</script>

MvcBlogum/MvcBlogPortfolio/Views/Yazar/YazarOl.cshtml
@{
    ViewBag.Title = "Yazar Ol";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>YazarOl</h2>


<form action="~/Yazar/YazarOl" method="post">
    <table class="table">
        <tr>
            <td>Adı:</td>
            <td><input type="text" name="Adi" value="" /></td>
        </tr>
        <tr>
            <td>Soyadı:</td>
            <td><input type="text" name="Soyadi" value="" /></td>
        </tr>
        <tr>
            <td> Kullanıcı Adı:</td>
            <td><input type="text" name="KullaniciAdi" value="" /></td>
        </tr>
        <tr>
            <td>Parola</td>
            <td><input type="password" name="Parola" value="" /></td>
        </tr>

        <tr>
            <td>Mail</td>
            <td><input type="text" name="MailAdres" value="" /></td>
        </tr>
        <tr>
            <td>Cinsiyet</td>
            <td><input type="radio" name="rdBay" value="Bay" /><span>Bay</span>
            <input type="radio" name="rdBayan" value="Bayan" /><span>Bayan</span></td>
        </tr>
        <tr>
            <td>Doğum Tarihi</td>
            <td><input type="date" name="DogumTarihi" value="" /></td>
        </tr>
        <tr>
            <td>Özgeçmiş</td>
            <td><input type="text" name="Aciklama" value="" /></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" name="name" value="Üye Ol" /></td>
        </tr>
    </table>
</form>

MvcBlogum/MvcBlogPortfolio/Views/Yazar/YazarınMakaleleri.cshtml
@model MvcBlogPortfolio.Tools.Myblog

@{
    ViewBag.Title = "YazarınMakaleleri";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<p>
    @Html.ActionLink("Yeni Makale Ekle", "Ekle","Makale")
</p>

    <table class="table">
        <tr>
            <th>Kategori Adı</th>
            <th>Kullanıcı Adı</th>
            <th>Resim</th>
            <th>Başlık</th>
            <th>İçerik</th>
            <th>Ekleme Tarihi</th>
            <th>Görüntülenme Sayısı</th>
            <th>Beğenme Sayısı</th>
            <th>Güncelle</th>
            <th>Sil</th>
            <th></th>
        </tr>

        @foreach (var item in Model.makaleler)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Kategori.KategoriAdi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kullanicilar.Adi)
                </td>
                <td>
                    <img src="@item.Resim.KucukBoyut" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Baslik)
                </td>
                <td>
                    @if (item.Icerik.Length >= 20)
                {
                        @Html.DisplayFor(modelItem => item.Icerik).ToString().Substring(0, 20);
                }
                else
                {
                        @Html.DisplayFor(modelItem => item.Icerik)
                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EklenmeTarihi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GoruntulenmeSayisi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Begeni)
                </td>
                <td>@Html.ActionLink("Guncelle", "Guncelle", new { id = item.MakaleId }) |</td>
                <td>@Html.ActionLink("Sil", "MakaleSil", new { id = item.MakaleId })</td>
            </tr>


        }
    </table>