MvcBlogum/MvcBlogPortfolio/Controllers/EtiketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogPortfolio.Controllers
{
    using Models;
    public class EtiketController : Controller
    {
        dbModelblog db = new dbModelblog();
        // GET: Etiket
        public ActionResult Index(int id)
        {
            return View(id);
        }

        public PartialViewResult EtiketleriListele()
        {
            return PartialView(db.Etiket.ToList());
        }

        public ActionResult MakaleListele(int id)
        {
            var data = db.Makale.Where(x => x.Etiket.Any(y => y.EtiketId == id)).ToList();
            return View("MakaleListele", data);
        }
        [Authorize(Roles ="Admin")]
        public ActionResult EtiketEkle()
        {
            return View();
        }
        [Authorize(Roles ="Admin")]
        [HttpPost]
        public ActionResult EtiketEkle(Etiket etiket)
        {
            Etiket etk = new Etiket();
            etk.EtiketAdi = etiket.EtiketAdi;
            etk.EtiketId = etiket.EtiketId;
            db.Etiket.Add(etk);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");

        }
    }
}

MvcBlogum/MvcBlogPortfolio/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogPortfolio.Controllers
{
    using Models;
    
    public class KategoriController : Controller
    {
        dbModelblog db = new dbModelblog();
        // GET: Kategori
        public ActionResult Index(int id)
        {
            return View(id);
        }

        public PartialViewResult KategoriListele()
        {
            return PartialView(db.Kategori.ToList());
        }

        public ActionResult MakaleListele(int id)
        {
            var data = db.Makale.Where(x => x.KategoriID == id).ToList();
            return View("MakaleListele", data);
        }
        [Authorize(Roles ="Admin")]
        public ActionResult KategoriEkle()
        {
            return View();
        }

        [Authorize(Roles ="Admin")]
        [HttpPost]
        public ActionResult KategoriEkle(Kategori kat)
        {
            Kategori kt = new Kategori();
            kt.KategoriAdi = kat.KategoriAdi;
            kt.KategoriId = kat.KategoriId;
            db.Kategori.Add(kt);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");

        }
    }
}

MvcBlogum/MvcBlogPortfolio/Views/Shared/Arama.cshtml
@{ 
    Layout = null;
}
<div class="sidebox widget">
    <h3 class="widget-title section-title">Ara</h3>
    <form class="~/Home/Ara" action="~/Home/Ara" method="post">
        <label><i class="icon-search"></i></label>
        <input type="text" id="s2" name="content" value="Birşeyler ara" onfocus="this.value=''" onblur="this.value='Search something'" />
        <button type="submit" class="btn">ARA</button>
    </form>
</div>

MvcBlogum/MvcBlogPortfolio/Views/Shared/MakaleListeleWidget.cshtml
@model IEnumerable<MvcBlogPortfolio.Models.Makale>

<script src="~/Content/style/js/jquery.min.js"></script>
<script>
    $(document).ready(function myfunction() {
        $("a.begen").click(function myfunction() {
            var id = $(this).data("id");
            var link = "/Makale/Begen/" + id;
            $.ajax({
                type: "GET",
                url: link,
                success: function (result) {
                    $("a.begen").html(result);
                }
            });
        });
    });
</script>

@section head{
        <script src="~/Content/style/js/jquery.min.js"></script>
        <script>
            $(document).ready(function myfunction() {
                $("a.goruntulenmesayisi").click(function myfunction() {
                    var id = $(this).data("id");
                    var link = "/Makale/Goruntulendi/" + id;
                    $.ajax({
                        type: "GET",
                        url: link,
                        success: function myfunction(result) {
                            $("a.goruntulenmesayisi").html(result);

                        }
                    });
                });
            });
        </script>
    }



@helper IcerikKisalt(string metin)
{
if (metin.Length > 300)
{
        @metin.Substring(0, 300)
}
else
{
        @metin
}
}

<div class="blog-posts col-blog">
    @foreach (MvcBlogPortfolio.Models.Makale mkl in Model)
    {
        <div class="post row">
            <div class="col-sm-4">
                <figure>
                    <a href="~/Makale/Detay/@mkl.MakaleId">
                        <div class="text-overlay">
                            <div class="info"><span>Daha Fazla</span></div>
                        </div>
                        <img src="@mkl.Resim.OrtaBoyut" alt="" />
                    </a>
                </figure>
            </div>
            <div class="col-sm-8 post-content">
                <div class="meta">
                    <span class="date">@mkl.EklenmeTarihi</span>
                    <span class="comments"><a href="#">@mkl.Yorum.Count <i class="icon-chat-1"> </i></a></span>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <span>
                            <a class="begen" href="javascript:void(0)" data-id="@mkl.MakaleId">
                                @mkl.Begeni
                                <img src="~/Content/image/like.png" />
                            </a>
                        </span>
                    }

                    <span>
                        <a class="goruntulenmesayisi" href="#" data-id="@mkl.MakaleId">
                            @mkl.GoruntulenmeSayisi
                            <img src="~/Content/image/view.png" />
                        </a>
                    </span>
               

                </div>
                <h2 class="post-title"><a href="~/Makale/Detay/@mkl.MakaleId">@mkl.Baslik</a></h2>
                     @IcerikKisalt(mkl.Icerik)
            </div>
        </div>
    }
</div>

MvcBlogum/MvcBlogPortfolio/Views/Shared/SiteHakkinda.cshtml
<div class="sidebox widget">
    <h3 class="widget-title section-title">SİTE HAKKINDA</h3>
    <p>C# ile PROGRAMLAMA</p>
    <ul class="social">
        <li><a href="#"><i class="icon-s-rss"></i></a></li>
        <li><a href="#"><i class="icon-s-twitter"></i></a></li>
        <li><a href="#"><i class="icon-s-facebook"></i></a></li>
        <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
        <li><a href="#"><i class="icon-s-linkedin"></i></a></li>
        <li><a href="#"><i class="icon-s-dribbble"></i></a></li>
        <li><a href="#"><i class="icon-s-flickr"></i></a></li>
    </ul>
    <div class="clearfix"></div>
</div>

MvcBlogum/MvcBlogPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="style/images/favicon.png">
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/bootstrap.js"></script>

    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="~/ckfinder/ckfinder.js"></script>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/style/css/style.css" rel="stylesheet" />
    <link href="~/Content/style/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/style/css/plugins.css" rel="stylesheet" />
   
    <link href="~/Content/style/css/color/red.css" rel="stylesheet" />
    <link href="~/Content/style/type/bebas.css" rel="stylesheet" />
    <link href="~/Content/style/type/fontello.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
          <script src="style/js/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
          <![endif]-->
    @RenderSection("head", false);
</head>
<body>
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
    <div class="body-wrapper">
        <div class="navbar default">
            <div class="navbar-header">
                <div class="container">
                    <div class="basic-wrapper">
                        <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i></i></a>
                        <div class="navbar-brand"><a href="~/Home/Index">LOGO </a></div>
                    </div>
                    <nav class="collapse navbar-collapse pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="~/Home/Index">Anasayfa</a></li>
                            @if (User.IsInRole("Yazar"))
                            {
                                <li class="current dropdown">
                                    <a href="~/Yazar/Index" class="dropdown-toggle js-activated">Yazar Paneli</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="~/Makale/Ekle">MakaleEkle</a></li>
                                        <li><a href="~/Yazar/YazarınMakaleleri">Makalelerim</a></li>
                                    </ul>
                                </li>
                      
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="dropdown">
                                    <a href="~/Admin/Index" class="dropdown-toggle js-activated">Admin Paneli</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="~/Makale/Ekle">Makale Ekle</a></li>
                                        <li><a href="~/Kategori/KategoriEkle">Kategori Ekle</a></li>
                                        <li><a href="~/Etiket/EtiketEkle">Etiket Ekle</a></li>
                                        <li><a href="~/Admin/RolEkle">Rol Ekle</a></li>
                                        <li><a href="~/Admin/KullaniciEkle">Kullanıcı Ekle</a></li>
                                        <li><a href="~/Admin/YazarOnaylari">Yazar Onayları </a></li>
                                        <li><a href="~/Admin/YazarlariListele">Yazar Listele </a></li>
                                    </ul>
                                </li>
                            }
                            
                         @if (!User.IsInRole("Yazar") || !User.Identity.IsAuthenticated || !User.IsInRole("Admin"))
                         {
                            <li>
                                <a href="~/Yazar/YazarOl">Yazar Ol</a>
                            </li>
                         }

                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a href="~/Kullanici/UyeOl">Üye Ol</a>
                                </li>
                            }


                       
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li><a href="~/Kullanici/CikisYap/@Session["KullaniciId"]">Çıkış Yap</a></li>
                            }
                            else
                            {
                                <li><a href="~/Kullanici/GirisYap">Giriş Yap</a></li>
                            }

                       
                            <li class="dropdown social-dropdown pull-right">
                                <div class="share btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="icon-heart-1"></i></div>
                                <ul class="button-group dropdown-menu dropdown-menu-right share-links">
                                    <li><a href="www.facebook.com" class="btn"><i class="icon-s-facebook"></i></a></li>
                                    <li><a href="www.twitter.com" class="btn"><i class="icon-s-twitter"></i></a></li>
                                </ul>
                            </li>
                            <!--/social-dropdown -->
                        </ul>
                        <!--/.navbar-nav -->
                    </nav>
                    <!--/.nav-collapse -->
                </div>
                <!--/.container -->
            </div>
            <!--/.navbar-header -->
        </div>
        <!--/.navbar -->
        <div class="offset"></div>
        <div class="dark-wrapper page-title">
            <div class="container inner">
                <h1> BLOGUM </h1>
            </div>
            <!--/.container -->
        </div>
        <!--/.page-title -->

        <div class="container inner">
            <div class="row">
                <div class="col-sm-8 content">

                    @RenderBody()
                </div>
                <aside class="col-sm-4 sidebar lp30">
                    @{
                        Html.RenderPartial("Arama");
                    }
                    @{ 
                        Html.RenderAction("KategoriListele", "Kategori");
                    }
                    @{ 
                        Html.RenderAction("PopulerMakalelerWidget", "Home");
                    }
                    @{ 
                        Html.RenderPartial("SiteHakkinda");
                    }

                    @{ 
                        Html.RenderAction("EtiketleriListele", "Etiket");
                    }
                </aside>
            </div>
        </div>
        <footer class="footer black-wrapper">
            <div class="container inner">
                <div class="row">

                    <div class="col-sm-3">
                        <div class="widget">
                            @{
                                Html.RenderAction("PopulerMakalelerWidget", "Home");
                            }
                            <!-- /.post-list -->
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            @{
                                Html.RenderAction("KategoriListele", "Kategori");
                            }
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">Site Hakkında</h3>
                            <p>Gönüllü yazarların kendilerine ait makalerini paylaşabileceği bir platformdur. </p>
                            <div class="contact-info">
                                <i class="icon-location"></i>BLOG<br />
                                <i class="icon-phone"></i>+00 (123) 456 78 90 <br />
                                <i class="icon-mobile"></i>+80 (547) 455 47 54 <br />
                                <i class="icon-mail"></i> <a href="first.last@email.com">blogblog@email.com</a>
                            </div>
                        </div>
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            @{
                                Html.RenderAction("EtiketleriListele", "Etiket");
                            }
                            <!-- /.tag-list -->
                        </div>
                        <!-- /.widget -->

                        <div class="widget">
                            @{
                                Html.RenderPartial("SiteHakkinda");
                            }
                        </div>
                        <!-- /.widget -->

                    </div>
                    <!-- /column -->

                </div>
                <!-- /.row -->
            </div>
            <!-- .container -->

            <div class="sub-footer">
                <div class="container">
                    <p class="pull-left">@DateTime.Now.Year &copy; Tüm Hakları Saklıdır. </p>
                    <ul class="footer-menu pull-right">
                        <li><a href="~/Home/Index">Anasayfa</a></li>
                        <li><a href="#">Hakkımda</a></li>
                        <li><a href="#">Calısmalarım</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">İletisim</a></li>
                    </ul>
                </div>
            </div>
        </footer>
        <!-- /footer -->
    </div>
    <!--/.body-wrapper -->
    <script src="~/Content/style/js/jquery.min.js"></script>
    <script src="~/Content/style/js/bootstrap.min.js"></script>
    <script src="~/Content/style/js/plugins.js"></script>
    <script src="~/Content/style/js/scripts.js"></script>
</body>
</html>

MvcBlogum/MvcBlogPortfolio/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon" href="style/images/favicon.png">
<meta name="viewport" content="width=device-width" />
<script src="~/Scripts/bootstrap.js"></script>

<script src="~/ckeditor/ckeditor.js"></script>
<script src="~/ckfinder/ckfinder.js"></script>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<!-- Bootstrap core CSS -->
<link href="~/Content/style/css/style.css" rel="stylesheet" />
<link href="~/Content/style/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/style/css/plugins.css" rel="stylesheet" />

<link href="~/Content/style/css/color/red.css" rel="stylesheet" />
<link href="~/Content/style/type/bebas.css" rel="stylesheet" />
<link href="~/Content/style/type/fontello.css" rel="stylesheet" />
<title>@ViewBag.Title</title>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="style/js/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
@RenderSection("head", false);
</head>
<body>
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
    <div class="body-wrapper">
        <div class="navbar default">
            <div class="navbar-header">
                <div class="container">
                    <div class="basic-wrapper">
                        <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i></i></a>
                        <div class="navbar-brand"><a href="~/Home/Index">LOGO </a></div>
                    </div>
                    <nav class="collapse navbar-collapse pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="~/Home/Index">Anasayfa</a></li>
                            @if (User.IsInRole("Yazar"))
                            {
                                <li class="current dropdown">
                                    <a href="~/Yazar/Index" class="dropdown-toggle js-activated">Yazar Paneli</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="~/Makale/Ekle">MakaleEkle</a></li>
                                        <li><a href="~/Yazar/YazarınMakaleleri">Makalelerim</a></li>
                                    </ul>
                                </li>

                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="dropdown">
                                    <a href="~/Admin/Index" class="dropdown-toggle js-activated">Admin Paneli</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="~/Makale/Ekle">Makale Ekle</a></li>
                                        <li><a href="~/Kategori/KategoriEkle">Kategori Ekle</a></li>
                                        <li><a href="~/Etiket/EtiketEkle">Etiket Ekle</a></li>
                                        <li><a href="~/Admin/RolEkle">Rol Ekle</a></li>
                                        <li><a href="~/Admin/KullaniciEkle">Kullanıcı Ekle</a></li>
                                        <li><a href="~/Admin/YazarOnaylari">Yazar Onayları </a></li>
                                        <li><a href="~/Admin/YazarlariListele">Yazar Listele </a></li>
                                    </ul>
                                </li>
                            }

                            @if (!User.IsInRole("Yazar") || !User.Identity.IsAuthenticated || !User.IsInRole("Admin"))
                            {
                                <li>
                                    <a href="~/Yazar/YazarOl">Yazar Ol</a>
                                </li>
                            }

                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a href="~/Kullanici/UyeOl">Üye Ol</a>
                                </li>
                            }






                            @if (User.Identity.IsAuthenticated)
                            {
                                <li><a href="~/Kullanici/CikisYap/@Session["KullaniciId"]">Çıkış Yap</a></li>
                            }
                            else
                            {
                                <li><a href="~/Kullanici/GirisYap">Giriş Yap</a></li>
                            }
                            <li class="dropdown social-dropdown pull-right">
                                <div class="share btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="icon-heart-1"></i></div>
                                <ul class="button-group dropdown-menu dropdown-menu-right share-links">
                                    <li><a href="www.facebook.com" class="btn"><i class="icon-s-facebook"></i></a></li>
                                    <li><a href="www.twitter.com" class="btn"><i class="icon-s-twitter"></i></a></li>
                                </ul>
                            </li>
                            <!--/social-dropdown -->
                        </ul>
                        <!--/.navbar-nav -->
                    </nav>
                    <!--/.nav-collapse -->
                </div>
                <!--/.container -->
            </div>
            <!--/.navbar-header -->
        </div>
        <!--/.navbar -->
        <div class="offset"></div>
        <div class="dark-wrapper page-title">
            <div class="container inner">
                <h1> BLOG </h1>
            </div>
            <!--/.container -->
        </div>
        <!--/.page-title -->

        <div class="container inner">
            <div class="row">
         

                    @RenderBody()
               

            </div>
        </div>
        <footer class="footer black-wrapper">
            <div class="container inner">
                <div class="row">

                    <div class="col-sm-3">
                        <div class="widget">
                            @{
                                Html.RenderAction("PopulerMakalelerWidget", "Home");
                            }
                            <!-- /.post-list -->
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            @{
                                Html.RenderAction("KategoriListele", "Kategori");
                            }
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">Get In Touch</h3>
                            <p>Fusce dapibus, tellus commodo, tortor mauris condimentum utellus fermentum, porta sem malesuada magna. Sed posuere consectetur est at lobortis.</p>
                            <div class="contact-info">
                                <i class="icon-location"></i> Moonshine St. 14/05 Light City <br />
                                <i class="icon-phone"></i>+00 (123) 456 78 90 <br />
                                <i class="icon-mobile"></i>+80 (547) 455 47 54 <br />
                                <i class="icon-mail"></i> <a href="first.last@email.com">first.last@email.com</a>
                            </div>
                        </div>
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            @{
                                Html.RenderAction("EtiketleriListele", "Etiket");
                            }
                            <!-- /.tag-list -->
                        </div>
                        <!-- /.widget -->

                        <div class="widget">
                            @{
                                Html.RenderPartial("SiteHakkinda");
                            }
                        </div>
                        <!-- /.widget -->

                    </div>
                    <!-- /column -->

                </div>
                <!-- /.row -->
            </div>
            <!-- .container -->

            <div class="sub-footer">
                <div class="container">
                    <p class="pull-left">@DateTime.Now.Year &copy; Tüm Hakları Saklıdır. </p>
                    <ul class="footer-menu pull-right">
                        <li><a href="~/Home/Index">Anasayfa</a></li>
                        <li><a href="#">Hakkımda</a></li>
                        <li><a href="#">Calısmalarım</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">İletisim</a></li>
                    </ul>
                </div>
            </div>
        </footer>
        <!-- /footer -->
    </div>
    <!--/.body-wrapper -->
    <script src="~/Content/style/js/jquery.min.js"></script>
    <script src="~/Content/style/js/bootstrap.min.js"></script>
    <script src="~/Content/style/js/plugins.js"></script>
    <script src="~/Content/style/js/scripts.js"></script>
</body>
</html>